import React from 'react';
import { Tile } from '@carbon/react';
import { WatsonHealth3DCursor, Light } from '@carbon/icons-react';
import './AIInsights.scss';

const AIInsights = ({ insights }) => {
  return (
    <Tile className="ai-insights">
      <div className="insights-header">
        <WatsonHealth3DCursor size={24} />
        <h3>IBM Bob AI Analysis</h3>
      </div>

      <div className="insights-content">
        <div className="insights-intro">
          <Light size={20} />
          <p>AI-powered reasoning and optimization recommendations</p>
        </div>

        <div className="insights-list">
          {insights.map((insight, index) => (
            <div key={index} className="insight-item">
              <div className="insight-number">{index + 1}</div>
              <div className="insight-text">{insight}</div>
            </div>
          ))}
        </div>

        <div className="insights-footer">
          <p className="footer-note">
            <strong>Note:</strong> These insights are generated by IBM Bob's reasoning engine 
            based on the simulated I/O journey through the FlashSystem topology.
          </p>
        </div>
      </div>
    </Tile>
  );
};

export default AIInsights;

// Made with Bob
